
// Generated by Cadence Genus(TM) Synthesis Solution GENUS15.20 - 15.20-p004_1
// Generated on: May 18 2022 13:02:51

// Verification Directory fv/Adder 

module Adder(A, B, cin, S, cout);
  input [7:0] A, B;
  input cin;
  output [7:0] S;
  output cout;
  wire [7:0] A, B;
  wire cin;
  wire [7:0] S;
  wire cout;
  wire n_33, n_35, n_36, n_37, n_39, n_40, n_41, n_43;
  wire n_58, n_59, n_60, n_61, n_63, n_64, n_65, n_66;
  wire n_68, n_69, n_70, n_71, n_72, n_74, n_75, n_76;
  wire n_77, n_84, n_85, n_86, n_87, n_88, n_90, n_91;
  wire n_92, n_97, n_98, n_99, n_100, n_101, n_102, n_103;
  wire n_104, n_107, n_108, n_109, n_110, n_111, n_113, n_114;
  wire n_115, n_116, n_118, n_119, n_120, n_121, n_122, n_123;
  wire n_124, n_125, n_126, n_127, n_128, n_129, n_130, n_131;
  wire n_132, n_136, n_138, n_139;
  INVXL g904(.A (n_40), .Y (n_41));
  OAI21XL g905(.A0 (n_37), .A1 (n_75), .B0 (n_39), .Y (n_40));
  INVXL g912(.A (n_36), .Y (n_37));
  OAI21XL g913(.A0 (n_33), .A1 (n_77), .B0 (n_35), .Y (n_36));
  INVX1 g932(.A (n_69), .Y (n_33));
  NAND2XL g920(.A (A[3]), .B (B[3]), .Y (n_35));
  NAND2XL g923(.A (A[4]), .B (B[4]), .Y (n_39));
  NAND2XL g917(.A (A[5]), .B (B[5]), .Y (n_43));
  OAI221XL g892(.A0 (n_59), .A1 (B[5]), .B0 (n_41), .B1 (n_43), .C0
       (n_61), .Y (S[5]));
  NAND2XL g901(.A (n_58), .B (n_40), .Y (n_59));
  INVXL g933(.A (A[5]), .Y (n_58));
  AOI31XL g895(.A0 (n_41), .A1 (n_58), .A2 (B[5]), .B0 (n_60), .Y
       (n_61));
  NOR3XL g899(.A (n_40), .B (n_58), .C (B[5]), .Y (n_60));
  OAI221XL g896(.A0 (n_64), .A1 (B[4]), .B0 (n_37), .B1 (n_39), .C0
       (n_66), .Y (S[4]));
  NAND2XL g907(.A (n_63), .B (n_36), .Y (n_64));
  INVXL g934(.A (A[4]), .Y (n_63));
  AOI31XL g903(.A0 (n_37), .A1 (n_63), .A2 (B[4]), .B0 (n_65), .Y
       (n_66));
  NOR3XL g906(.A (n_36), .B (n_63), .C (B[4]), .Y (n_65));
  OR3XL g908(.A (n_68), .B (n_71), .C (n_72), .Y (S[3]));
  OAI32XL g914(.A0 (n_33), .A1 (B[3]), .A2 (A[3]), .B0 (n_33), .B1
       (n_35), .Y (n_68));
  NOR3XL g915(.A (n_69), .B (n_70), .C (A[3]), .Y (n_71));
  INVXL g926(.A (B[3]), .Y (n_70));
  AND3X1 g916(.A (n_33), .B (n_70), .C (A[3]), .Y (n_72));
  NOR2XL g953(.A (B[5]), .B (A[5]), .Y (n_74));
  NOR2XL g955(.A (B[4]), .B (A[4]), .Y (n_75));
  NOR2XL g948(.A (B[6]), .B (A[6]), .Y (n_76));
  NOR2XL g950(.A (B[3]), .B (A[3]), .Y (n_77));
  NOR3XL g629(.A (n_118), .B (n_121), .C (n_120), .Y (n_84));
  INVXL g956(.A (n_85), .Y (n_86));
  NAND2XL g957(.A (A[0]), .B (B[0]), .Y (n_85));
  NOR3XL g930(.A (n_118), .B (n_121), .C (n_87), .Y (n_88));
  NAND2XL g946(.A (A[1]), .B (B[1]), .Y (n_87));
  OAI21XL g940(.A0 (n_39), .A1 (n_74), .B0 (n_43), .Y (n_90));
  INVXL g947(.A (n_76), .Y (n_91));
  NOR4BXL g939(.AN (n_91), .B (n_35), .C (n_74), .D (n_75), .Y (n_92));
  OAI221XL g630(.A0 (n_101), .A1 (B[2]), .B0 (n_102), .B1 (n_123), .C0
       (n_104), .Y (S[2]));
  NAND2XL g927(.A (n_97), .B (n_100), .Y (n_101));
  INVXL g961(.A (A[2]), .Y (n_97));
  OAI21XL g631(.A0 (n_99), .A1 (n_120), .B0 (n_87), .Y (n_100));
  AOI2BB1XL g942(.A0N (n_119), .A1N (n_98), .B0 (n_86), .Y (n_99));
  INVXL g958(.A (cin), .Y (n_98));
  INVXL g632(.A (n_100), .Y (n_102));
  AOI31XL g633(.A0 (n_102), .A1 (n_97), .A2 (B[2]), .B0 (n_103), .Y
       (n_104));
  NOR3XL g634(.A (n_100), .B (n_97), .C (B[2]), .Y (n_103));
  OAI21XL g635(.A0 (n_102), .A1 (n_121), .B0 (n_123), .Y (n_69));
  OAI221XL g636(.A0 (n_109), .A1 (B[1]), .B0 (n_99), .B1 (n_87), .C0
       (n_111), .Y (S[1]));
  NAND2XL g936(.A (n_107), .B (n_108), .Y (n_109));
  INVXL g959(.A (A[1]), .Y (n_107));
  INVXL g941(.A (n_99), .Y (n_108));
  AOI31XL g637(.A0 (n_99), .A1 (n_107), .A2 (B[1]), .B0 (n_110), .Y
       (n_111));
  NOR3XL g935(.A (n_108), .B (n_107), .C (B[1]), .Y (n_110));
  OR3XL g937(.A (n_113), .B (n_115), .C (n_116), .Y (S[0]));
  OAI32XL g943(.A0 (n_98), .A1 (B[0]), .A2 (A[0]), .B0 (n_85), .B1
       (n_98), .Y (n_113));
  NOR3XL g944(.A (n_114), .B (A[0]), .C (cin), .Y (n_115));
  INVXL g960(.A (B[0]), .Y (n_114));
  AND3X1 g945(.A (n_114), .B (n_98), .C (A[0]), .Y (n_116));
  OAI221XL g329(.A0 (n_127), .A1 (n_130), .B0 (n_127), .B1 (n_131), .C0
       (n_132), .Y (S[7]));
  AOI21XL g333(.A0 (n_122), .A1 (cin), .B0 (n_126), .Y (n_127));
  NOR4XL g337(.A (n_118), .B (n_119), .C (n_120), .D (n_121), .Y
       (n_122));
  OR4X1 g340(.A (n_77), .B (n_76), .C (n_74), .D (n_75), .Y (n_118));
  NOR2XL g346(.A (B[0]), .B (A[0]), .Y (n_119));
  NOR2XL g344(.A (B[1]), .B (A[1]), .Y (n_120));
  NOR2XL g342(.A (B[2]), .B (A[2]), .Y (n_121));
  OAI211XL g336(.A0 (n_118), .A1 (n_123), .B0 (n_124), .C0 (n_125), .Y
       (n_126));
  NAND2XL g343(.A (A[2]), .B (B[2]), .Y (n_123));
  AOI21XL g339(.A0 (n_84), .A1 (n_86), .B0 (n_88), .Y (n_124));
  AOI221XL g338(.A0 (n_91), .A1 (n_90), .B0 (A[6]), .B1 (B[6]), .C0
       (n_92), .Y (n_125));
  NAND2XL g345(.A (n_128), .B (n_129), .Y (n_130));
  INVXL g348(.A (A[7]), .Y (n_128));
  INVXL g347(.A (B[7]), .Y (n_129));
  NAND2XL g341(.A (A[7]), .B (B[7]), .Y (n_131));
  AOI33XL g330(.A0 (n_127), .A1 (n_129), .A2 (A[7]), .B0 (n_127), .B1
       (B[7]), .B2 (n_128), .Y (n_132));
  NAND2XL g331(.A (n_138), .B (n_136), .Y (cout));
  AOI22XL g332(.A0 (n_126), .A1 (n_130), .B0 (A[7]), .B1 (B[7]), .Y
       (n_136));
  NAND3X1 g2(.A (n_122), .B (n_130), .C (cin), .Y (n_138));
  XOR3X2 g638(.A (n_139), .B (B[6]), .C (A[6]), .Y (S[6]));
  OAI21XL g3(.A0 (n_41), .A1 (n_74), .B0 (n_43), .Y (n_139));
endmodule

