============================================================
  Generated by:           Genus(TM) Synthesis Solution GENUS15.20 - 15.20-p004_1
  Generated on:           May 18 2022  06:59:29 pm
  Module:                 KoggeStoneAdder
  Technology library:     typical 1.1
  Operating conditions:   typical (balanced_tree)
  Wireload mode:          enclosed
  Area mode:              timing library
============================================================

  Pin       Type     Fanout Load Slew Delay Arrival   
                            (fF) (ps)  (ps)   (ps)    
------------------------------------------------------
Ci         in port        5 20.2    0    +0       0 F 
GB47/Gki 
  g17/A1                                 +0       0   
  g17/Y    AOI21X1        1  2.7  111   +92      92 R 
  g16/A                                  +0      92   
  g16/Y    INVXL          1  0.0   30   +19     111 F 
GB47/G 
Co         out port                      +0     111 F 
------------------------------------------------------
Exception    : 'path_delays/del_3'    1000ps
Timing slack :     889ps 
Start-point  : Ci
End-point    : Co
