
// Generated by Cadence Genus(TM) Synthesis Solution GENUS15.20 - 15.20-p004_1
// Generated on: May 18 2022 18:29:26

// Verification Directory fv/KoggeStoneAdder 

module PgCell(Ai, Bi, Pi, Gi);
  input Ai, Bi;
  output Pi, Gi;
  wire Ai, Bi;
  wire Pi, Gi;
  ADDHXL g17(.A (Bi), .B (Ai), .S (Pi), .CO (Gi));
endmodule

module PgCell_6(Ai, Bi, Pi, Gi);
  input Ai, Bi;
  output Pi, Gi;
  wire Ai, Bi;
  wire Pi, Gi;
  ADDHXL g17(.A (Bi), .B (Ai), .S (Pi), .CO (Gi));
endmodule

module PgCell_7(Ai, Bi, Pi, Gi);
  input Ai, Bi;
  output Pi, Gi;
  wire Ai, Bi;
  wire Pi, Gi;
  ADDHXL g17(.A (Bi), .B (Ai), .S (Pi), .CO (Gi));
endmodule

module GrayCell_1(Pi, Gi, Gki, G);
  input Pi, Gi, Gki;
  output G;
  wire Pi, Gi, Gki;
  wire G;
  wire n_0;
  INVX1 g16(.A (n_0), .Y (G));
  AOI21XL g17(.A0 (Pi), .A1 (Gki), .B0 (Gi), .Y (n_0));
endmodule

module GrayCell_8(Pi, Gi, Gki, G);
  input Pi, Gi, Gki;
  output G;
  wire Pi, Gi, Gki;
  wire G;
  wire n_0;
  INVX1 g16(.A (n_0), .Y (G));
  AOI21XL g17(.A0 (Pi), .A1 (Gki), .B0 (Gi), .Y (n_0));
endmodule

module GrayCell_9(Pi, Gi, Gki, G);
  input Pi, Gi, Gki;
  output G;
  wire Pi, Gi, Gki;
  wire G;
  wire n_0;
  INVX1 g16(.A (n_0), .Y (G));
  AOI21XL g17(.A0 (Gki), .A1 (Pi), .B0 (Gi), .Y (n_0));
endmodule

module GrayCell_15(Pi, Gi, Gki, G);
  input Pi, Gi, Gki;
  output G;
  wire Pi, Gi, Gki;
  wire G;
  wire n_0;
  INVXL g16(.A (n_0), .Y (G));
  AOI21XL g17(.A0 (Pi), .A1 (Gki), .B0 (Gi), .Y (n_0));
endmodule

module GrayCell_16(Pi, Gi, Gki, G);
  input Pi, Gi, Gki;
  output G;
  wire Pi, Gi, Gki;
  wire G;
  wire n_0;
  INVXL g16(.A (n_0), .Y (G));
  AOI21XL g17(.A0 (Pi), .A1 (Gki), .B0 (Gi), .Y (n_0));
endmodule

module GrayCell_17(Pi, Gi, Gki, G);
  input Pi, Gi, Gki;
  output G;
  wire Pi, Gi, Gki;
  wire G;
  wire n_0;
  INVXL g16(.A (n_0), .Y (G));
  AOI21XL g17(.A0 (Gki), .A1 (Pi), .B0 (Gi), .Y (n_0));
endmodule

module GrayCell_18(Pi, Gi, Gki, G);
  input Pi, Gi, Gki;
  output G;
  wire Pi, Gi, Gki;
  wire G;
  wire n_0;
  INVXL g16(.A (n_0), .Y (G));
  AOI21XL g17(.A0 (Gki), .A1 (Pi), .B0 (Gi), .Y (n_0));
endmodule

module GrayCell_20(Pi, Gi, Gki, G);
  input Pi, Gi, Gki;
  output G;
  wire Pi, Gi, Gki;
  wire G;
  wire n_0;
  INVXL g16(.A (n_0), .Y (G));
  AOI21X1 g17(.A0 (Pi), .A1 (Gki), .B0 (Gi), .Y (n_0));
endmodule

module GrayCell(Pi, Gi, Gki, G);
  input Pi, Gi, Gki;
  output G;
  wire Pi, Gi, Gki;
  wire G;
  wire n_0;
  INVX1 g16(.A (n_0), .Y (G));
  AOI21XL g17(.A0 (Pi), .A1 (Gki), .B0 (Gi), .Y (n_0));
endmodule

module BlackCell(Pi, Gi, Pki, Gki, P, G);
  input Pi, Gi, Pki, Gki;
  output P, G;
  wire Pi, Gi, Pki, Gki;
  wire P, G;
  GrayCell gcell(.Pi (Pi), .Gi (Gi), .Gki (Gki), .G (G));
  AND2X1 g8(.A (Pki), .B (Pi), .Y (P));
endmodule

module GrayCell_2(Pi, Gi, Gki, G);
  input Pi, Gi, Gki;
  output G;
  wire Pi, Gi, Gki;
  wire G;
  wire n_0;
  INVX1 g16(.A (n_0), .Y (G));
  AOI21XL g17(.A0 (Pi), .A1 (Gki), .B0 (Gi), .Y (n_0));
endmodule

module BlackCell_1(Pi, Gi, Pki, Gki, P, G);
  input Pi, Gi, Pki, Gki;
  output P, G;
  wire Pi, Gi, Pki, Gki;
  wire P, G;
  GrayCell_2 gcell(.Pi (Pi), .Gi (Gi), .Gki (Gki), .G (G));
  AND2X1 g8(.A (Pki), .B (Pi), .Y (P));
endmodule

module GrayCell_3(Pi, Gi, Gki, G);
  input Pi, Gi, Gki;
  output G;
  wire Pi, Gi, Gki;
  wire G;
  wire n_0;
  INVX1 g16(.A (n_0), .Y (G));
  AOI21XL g17(.A0 (Pi), .A1 (Gki), .B0 (Gi), .Y (n_0));
endmodule

module BlackCell_2(Pi, Gi, Pki, Gki, P, G);
  input Pi, Gi, Pki, Gki;
  output P, G;
  wire Pi, Gi, Pki, Gki;
  wire P, G;
  GrayCell_3 gcell(.Pi (Pi), .Gi (Gi), .Gki (Gki), .G (G));
  AND2X1 g8(.A (Pki), .B (Pi), .Y (P));
endmodule

module GrayCell_4(Pi, Gi, Gki, G);
  input Pi, Gi, Gki;
  output G;
  wire Pi, Gi, Gki;
  wire G;
  wire n_0;
  INVX1 g16(.A (n_0), .Y (G));
  AOI21XL g17(.A0 (Pi), .A1 (Gki), .B0 (Gi), .Y (n_0));
endmodule

module BlackCell_3(Pi, Gi, Pki, Gki, P, G);
  input Pi, Gi, Pki, Gki;
  output P, G;
  wire Pi, Gi, Pki, Gki;
  wire P, G;
  GrayCell_4 gcell(.Pi (Pi), .Gi (Gi), .Gki (Gki), .G (G));
  AND2X1 g8(.A (Pki), .B (Pi), .Y (P));
endmodule

module GrayCell_5(Pi, Gi, Gki, G);
  input Pi, Gi, Gki;
  output G;
  wire Pi, Gi, Gki;
  wire G;
  wire n_0;
  INVX1 g16(.A (n_0), .Y (G));
  AOI21XL g17(.A0 (Pi), .A1 (Gki), .B0 (Gi), .Y (n_0));
endmodule

module BlackCell_4(Pi, Gi, Pki, Gki, P, G);
  input Pi, Gi, Pki, Gki;
  output P, G;
  wire Pi, Gi, Pki, Gki;
  wire P, G;
  GrayCell_5 gcell(.Pi (Pi), .Gi (Gi), .Gki (Gki), .G (G));
  AND2X1 g8(.A (Pki), .B (Pi), .Y (P));
endmodule

module GrayCell_6(Pi, Gi, Gki, G);
  input Pi, Gi, Gki;
  output G;
  wire Pi, Gi, Gki;
  wire G;
  wire n_0;
  INVXL g16(.A (n_0), .Y (G));
  AOI21XL g17(.A0 (Pi), .A1 (Gki), .B0 (Gi), .Y (n_0));
endmodule

module BlackCell_5(Pi, Gi, Pki, Gki, P, G);
  input Pi, Gi, Pki, Gki;
  output P, G;
  wire Pi, Gi, Pki, Gki;
  wire P, G;
  GrayCell_6 gcell(.Pi (Pi), .Gi (Gi), .Gki (Gki), .G (G));
  AND2X1 g8(.A (Pki), .B (Pi), .Y (P));
endmodule

module GrayCell_7(Pi, Gi, Gki, G);
  input Pi, Gi, Gki;
  output G;
  wire Pi, Gi, Gki;
  wire G;
  wire n_0;
  INVXL g16(.A (n_0), .Y (G));
  AOI21XL g17(.A0 (Pi), .A1 (Gki), .B0 (Gi), .Y (n_0));
endmodule

module BlackCell_6(Pi, Gi, Pki, Gki, P, G);
  input Pi, Gi, Pki, Gki;
  output P, G;
  wire Pi, Gi, Pki, Gki;
  wire P, G;
  GrayCell_7 gcell(.Pi (Pi), .Gi (Gi), .Gki (Gki), .G (G));
  AND2X1 g8(.A (Pki), .B (Pi), .Y (P));
endmodule

module GrayCell_10(Pi, Gi, Gki, G);
  input Pi, Gi, Gki;
  output G;
  wire Pi, Gi, Gki;
  wire G;
  wire n_0;
  INVX1 g16(.A (n_0), .Y (G));
  AOI21XL g17(.A0 (Pi), .A1 (Gki), .B0 (Gi), .Y (n_0));
endmodule

module BlackCell_7(Pi, Gi, Pki, Gki, P, G);
  input Pi, Gi, Pki, Gki;
  output P, G;
  wire Pi, Gi, Pki, Gki;
  wire P, G;
  GrayCell_10 gcell(.Pi (Pi), .Gi (Gi), .Gki (Gki), .G (G));
  AND2X1 g8(.A (Pi), .B (Pki), .Y (P));
endmodule

module GrayCell_11(Pi, Gi, Gki, G);
  input Pi, Gi, Gki;
  output G;
  wire Pi, Gi, Gki;
  wire G;
  wire n_0;
  INVXL g16(.A (n_0), .Y (G));
  AOI21XL g17(.A0 (Pi), .A1 (Gki), .B0 (Gi), .Y (n_0));
endmodule

module BlackCell_8(Pi, Gi, Pki, Gki, P, G);
  input Pi, Gi, Pki, Gki;
  output P, G;
  wire Pi, Gi, Pki, Gki;
  wire P, G;
  GrayCell_11 gcell(.Pi (Pi), .Gi (Gi), .Gki (Gki), .G (G));
  AND2X1 g8(.A (Pki), .B (Pi), .Y (P));
endmodule

module GrayCell_12(Pi, Gi, Gki, G);
  input Pi, Gi, Gki;
  output G;
  wire Pi, Gi, Gki;
  wire G;
  wire n_0;
  INVXL g16(.A (n_0), .Y (G));
  AOI21XL g17(.A0 (Pi), .A1 (Gki), .B0 (Gi), .Y (n_0));
endmodule

module BlackCell_9(Pi, Gi, Pki, Gki, P, G);
  input Pi, Gi, Pki, Gki;
  output P, G;
  wire Pi, Gi, Pki, Gki;
  wire P, G;
  GrayCell_12 gcell(.Pi (Pi), .Gi (Gi), .Gki (Gki), .G (G));
  AND2X1 g8(.A (Pki), .B (Pi), .Y (P));
endmodule

module GrayCell_13(Pi, Gi, Gki, G);
  input Pi, Gi, Gki;
  output G;
  wire Pi, Gi, Gki;
  wire G;
  wire n_0;
  INVXL g16(.A (n_0), .Y (G));
  AOI21XL g17(.A0 (Gki), .A1 (Pi), .B0 (Gi), .Y (n_0));
endmodule

module BlackCell_10(Pi, Gi, Pki, Gki, P, G);
  input Pi, Gi, Pki, Gki;
  output P, G;
  wire Pi, Gi, Pki, Gki;
  wire P, G;
  GrayCell_13 gcell(.Pi (Pi), .Gi (Gi), .Gki (Gki), .G (G));
  AND2X1 g8(.A (Pki), .B (Pi), .Y (P));
endmodule

module GrayCell_14(Pi, Gi, Gki, G);
  input Pi, Gi, Gki;
  output G;
  wire Pi, Gi, Gki;
  wire G;
  wire n_0;
  INVXL g16(.A (n_0), .Y (G));
  AOI21XL g17(.A0 (Gki), .A1 (Pi), .B0 (Gi), .Y (n_0));
endmodule

module BlackCell_11(Pi, Gi, Pki, Gki, P, G);
  input Pi, Gi, Pki, Gki;
  output P, G;
  wire Pi, Gi, Pki, Gki;
  wire P, G;
  GrayCell_14 gcell(.Pi (Pi), .Gi (Gi), .Gki (Gki), .G (G));
  AND2X1 g8(.A (Pki), .B (Pi), .Y (P));
endmodule

module GrayCell_19(Pi, Gi, Gki, G);
  input Pi, Gi, Gki;
  output G;
  wire Pi, Gi, Gki;
  wire G;
  wire n_0;
  INVX1 g16(.A (n_0), .Y (G));
  AOI21XL g17(.A0 (Gki), .A1 (Pi), .B0 (Gi), .Y (n_0));
endmodule

module BlackCell_12(Pi, Gi, Pki, Gki, P, G);
  input Pi, Gi, Pki, Gki;
  output P, G;
  wire Pi, Gi, Pki, Gki;
  wire P, G;
  GrayCell_19 gcell(.Pi (Pi), .Gi (Gi), .Gki (Gki), .G (G));
  AND2X1 g8(.A (Pki), .B (Pi), .Y (P));
endmodule

module SumCell(Pi, Gki, Si);
  input Pi, Gki;
  output Si;
  wire Pi, Gki;
  wire Si;
  XOR2XL g10(.A (Gki), .B (Pi), .Y (Si));
endmodule

module SumCell_1(Pi, Gki, Si);
  input Pi, Gki;
  output Si;
  wire Pi, Gki;
  wire Si;
  XOR2XL g10(.A (Pi), .B (Gki), .Y (Si));
endmodule

module SumCell_2(Pi, Gki, Si);
  input Pi, Gki;
  output Si;
  wire Pi, Gki;
  wire Si;
  XOR2XL g10(.A (Pi), .B (Gki), .Y (Si));
endmodule

module SumCell_3(Pi, Gki, Si);
  input Pi, Gki;
  output Si;
  wire Pi, Gki;
  wire Si;
  XOR2XL g10(.A (Pi), .B (Gki), .Y (Si));
endmodule

module SumCell_4(Pi, Gki, Si);
  input Pi, Gki;
  output Si;
  wire Pi, Gki;
  wire Si;
  XOR2XL g10(.A (Pi), .B (Gki), .Y (Si));
endmodule

module SumCell_5(Pi, Gki, Si);
  input Pi, Gki;
  output Si;
  wire Pi, Gki;
  wire Si;
  XOR2XL g10(.A (Pi), .B (Gki), .Y (Si));
endmodule

module SumCell_7(Pi, Gki, Si);
  input Pi, Gki;
  output Si;
  wire Pi, Gki;
  wire Si;
  XOR2XL g10(.A (Pi), .B (Gki), .Y (Si));
endmodule

module KoggeStoneAdder(A, B, Ci, S, Co);
  input [7:0] A, B;
  input Ci;
  output [7:0] S;
  output Co;
  wire [7:0] A, B;
  wire Ci;
  wire [7:0] S;
  wire Co;
  wire G00, G01, G02, G03, G04, G05, G06, G07;
  wire G10, G11, G12, G13, G14, G15, G16, G17;
  wire G21, G22, G23, G24, G25, G26, G27, G33;
  wire G34, G35, G36, G37, P00, P01, P02, P03;
  wire P04, P05, P06, P07, P11, P12, P13, P14;
  wire P15, P16, P17, P23, P24, P25, P26, P27;
  wire P37;
  PgCell E0(.Ai (A[0]), .Bi (B[0]), .Pi (P00), .Gi (G00));
  PgCell E1(.Ai (A[1]), .Bi (B[1]), .Pi (P01), .Gi (G01));
  PgCell E2(.Ai (A[2]), .Bi (B[2]), .Pi (P02), .Gi (G02));
  PgCell E3(.Ai (A[3]), .Bi (B[3]), .Pi (P03), .Gi (G03));
  PgCell E4(.Ai (A[4]), .Bi (B[4]), .Pi (P04), .Gi (G04));
  PgCell E5(.Ai (A[5]), .Bi (B[5]), .Pi (P05), .Gi (G05));
  PgCell_6 E6(.Ai (A[6]), .Bi (B[6]), .Pi (P06), .Gi (G06));
  PgCell_7 E7(.Ai (A[7]), .Bi (B[7]), .Pi (P07), .Gi (G07));
  GrayCell_1 GB10(.Pi (P00), .Gi (G00), .Gki (Ci), .G (G10));
  GrayCell_8 GB21(.Pi (P11), .Gi (G11), .Gki (Ci), .G (G21));
  GrayCell_9 GB22(.Pi (P12), .Gi (G12), .Gki (G10), .G (G22));
  GrayCell_15 GB33(.Pi (P23), .Gi (G23), .Gki (Ci), .G (G33));
  GrayCell_16 GB34(.Pi (P24), .Gi (G24), .Gki (G10), .G (G34));
  GrayCell_17 GB35(.Pi (P25), .Gi (G25), .Gki (G21), .G (G35));
  GrayCell_18 GB36(.Pi (P26), .Gi (G26), .Gki (G22), .G (G36));
  GrayCell_20 GB47(.Pi (P37), .Gi (G37), .Gki (Ci), .G (Co));
  BlackCell PB11(.Pi (P01), .Gi (G01), .Pki (P00), .Gki (G00), .P (P11), .G (G11));
  BlackCell_1 PB12(.Pi (P02), .Gi (G02), .Pki (P01), .Gki (G01), .P (P12), .G (G12));
  BlackCell_2 PB13(.Pi (P03), .Gi (G03), .Pki (P02), .Gki (G02), .P (P13), .G (G13));
  BlackCell_3 PB14(.Pi (P04), .Gi (G04), .Pki (P03), .Gki (G03), .P (P14), .G (G14));
  BlackCell_4 PB15(.Pi (P05), .Gi (G05), .Pki (P04), .Gki (G04), .P (P15), .G (G15));
  BlackCell_5 PB16(.Pi (P06), .Gi (G06), .Pki (P05), .Gki (G05), .P (P16), .G (G16));
  BlackCell_6 PB17(.Pi (P07), .Gi (G07), .Pki (P06), .Gki (G06), .P (P17), .G (G17));
  BlackCell_7 PB23(.Pi (P13), .Gi (G13), .Pki (P11), .Gki (G11), .P (P23), .G (G23));
  BlackCell_8 PB24(.Pi (P14), .Gi (G14), .Pki (P12), .Gki (G12), .P (P24), .G (G24));
  BlackCell_9 PB25(.Pi (P15), .Gi (G15), .Pki (P13), .Gki (G13), .P (P25), .G (G25));
  BlackCell_10 PB26(.Pi (P16), .Gi (G16), .Pki (P14), .Gki (G14), .P (P26), .G (G26));
  BlackCell_11 PB27(.Pi (P17), .Gi (G17), .Pki (P15), .Gki (G15), .P (P27), .G (G27));
  BlackCell_12 PB37(.Pi (P27), .Gi (G27), .Pki (P23), .Gki (G23), .P (P37), .G (G37));
  SumCell S0(.Pi (P00), .Gki (Ci), .Si (S[0]));
  SumCell_1 S1(.Pi (P01), .Gki (G10), .Si (S[1]));
  SumCell_2 S2(.Pi (P02), .Gki (G21), .Si (S[2]));
  SumCell_3 S3(.Pi (P03), .Gki (G22), .Si (S[3]));
  SumCell_4 S4(.Pi (P04), .Gki (G33), .Si (S[4]));
  SumCell_5 S5(.Pi (P05), .Gki (G34), .Si (S[5]));
  SumCell_5 S6(.Pi (P06), .Gki (G35), .Si (S[6]));
  SumCell_7 S7(.Pi (P07), .Gki (G36), .Si (S[7]));
endmodule


    
